---

wordpress::params::install_dir: '/var/www'
wordpress::params::install_url: 'http://wordpess.org'
wordpress::params::version: '4.3.1'
wordpress::params::db_host: 'localhost'
wordpress::params::mysql_db_password: '9xzcxVQEB'
wordpress::params::wp_owner: 'www-data'
wordpress::params::wp_group: 'www-data'
wordpress::site_hash:
    'site_1':
        db_password: 'hrAF6n7J0JYqU'
        wp_lang: ''
        wp_plugin_dir: 'DEFAULT'
        wp_additional_config: 'DEFAULT'
        wp_table_prefix: 'wp_'
        wp_proxy_host: ''
        wp_proxy_port: ''
        wp_site_domain: 'site_1.com'
        wp_site_name: 'site_1.com'
        wp_site_title: 'site_1: Test'
        wp_admin: 'IXwUa4HQmbsaY'
        wp_admin_password: 'H/fGsTyXvi09vlOX9nuh'
        wp_admin_email: 'test@site_1.com'
        port: '8005'
    'site_2':
        db_password: 'hrAF6n7J0JYqU'
        wp_lang: ''
        wp_plugin_dir: 'DEFAULT'
        wp_additional_config: 'DEFAULT'
        wp_table_prefix: 'wp_'
        wp_proxy_host: ''
        wp_proxy_port: ''
        wp_site_domain: 'site_2.com'
        wp_site_name: 'site_2.com'
        wp_site_title: 'site_2: Test'
        wp_admin: 'IXwUa4HQmbsaY'
        wp_admin_password: 'H/fGsTyXvi09vlOX9nuh'
        wp_admin_email: 'test@site_1.com'
        wp_multisite: true
        port: '8006'
